extends:
  - next/core-web-vitals
  - standard-with-typescript
  - prettier
plugins:
  - unused-imports
parserOptions:
  project: tsconfig.json
rules:
  "@typescript-eslint/no-explicit-any": error
  "@typescript-eslint/consistent-type-definitions":
    - error
    - type
  "@typescript-eslint/return-await":
    - error
    - in-try-catch
  "unused-imports/no-unused-imports": error
  "unused-imports/no-unused-vars": error
  "import/order":
    - error
    - groups:
        - builtin
        - external
        - internal
      alphabetize:
        order: asc
        caseInsensitive: true
      newlines-between: always
      pathGroups:
        - pattern: src/**
          group: internal