name: Continuous Integration
run-name: Continuous Integration
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  lint:
    uses: yhiguchi-dev/reusable-workflow/.github/workflows/lint-with-pnpm.yaml@main
    with:
      node-version: ${{ matrix.node-version }}
      lint-command: lint
      working-directory: app
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 20
  build-and-lint-docker-image:
    uses: yhiguchi-dev/reusable-workflow/.github/workflows/docker-image.yaml@main
    with:
      build-context: ${{ matrix.build-context }}
      version: lint
      platform: ${{ matrix.platform }}
    needs:
      - lint
    strategy:
      fail-fast: false
      matrix:
        build-context:
          - app
        platform:
          - linux/amd64