name: CI
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  NEXT_PUBLIC_BACKEND_URL: ${{ secrets.BACKEND_URL }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 18
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
          cache-dependency-path: ./nextjs/pnpm-lock.yaml
      - name: Install dependencies
        run: pnpm install
        working-directory: nextjs
      - name: Run lint
        run: pnpm lint
        working-directory: nextjs
#      - name: Run test
#        run: pnpm test